import {Component, OnInit} from "@angular/core";
import {BaseCustomerKeysPipe} from "../pipe/base.customer.keys.pipe";
import {BaseValidateService} from "../service/base.validate.service";
import {BaseDataService} from "../service/base.data.service";
import {BaseFormCreateComponentNew} from "../baseComponent/base.from.create.component.new";
import {FormBuilder} from "@angular/forms";
import {Router} from "@angular/router";
import {BaseDateChooseDirective} from "../directive/base.date.choose";
import {UserLoginService} from "../service/login.service";


@Component({
  selector:"create-goods-form",
  templateUrl:"../baseComponent/base.from.create.component.new.html",
  styleUrls:["../baseComponent/base.from.create.component.css"],
  providers:[BaseCustomerKeysPipe,BaseValidateService,BaseDataService,BaseDateChooseDirective]
})
export class CreateGoodsFormComponent extends BaseFormCreateComponentNew implements OnInit{

  constructor(
    public formBuilder:FormBuilder,public baseValidateService:BaseValidateService,public baseDataService:BaseDataService,private router:Router,public userLoginService:UserLoginService
  ){
    super(formBuilder,baseDataService);
    console.log(userLoginService)
  }

  ngOnInit(){
    this.formModel={
      url:"goods/saveGoods.json",
      elements:[
        {
          type:"input",
          label:"商品类型",
          prop:"goodsType",
          removeValidateUrl:"",
          placeholder:"请输入商品类型",
          defaultValue:"",
          required:true,
          validates:[control=>{
            return this.baseValidateService.baseValidate(control,{required:true});
          }]
        },
        {
          type:"radio",
          label:"发放范围",
          prop:"serviceRange",
          removeValidateUrl:"",
          placeholder:"商品发布范围",
          defaultValue:"1",
          required:true,
          options:[
            {label:"自动覆盖店铺",value:1},
            {label:"自定范围",value:2}
          ],
          switcher:[
            {
              prop:"goodsType",
              showValue:1
            }
          ],
          validates:[data=>{
            let param={prop:"serviceRange",formModel:this.formModel};
            let error=this.baseValidateService.baseValidate(data,{watchers:true},param);
            return error;
          }]
        },
        {
          label:"选择服务范围",
          type:"baseAreaChoose",
          prop:"goodsServiceRangeDetail",
          defaultValue:"请输入商品服务范围",
          switcher:[
            {
              prop:"serviceRange",
              showValue:"2"
            }
          ]
        },
        {
          type:"select",
          label:"商品分类",
          prop:"goodsCategory",
          defaultValue:"",
          remoteInfo:{
            baseUrl:"https://testbackend.goodaa.com.cn/ejiazi-backend/",
            url:"indexPromotion/initJumpTypes.json",
            httpMethod:"post",
            param:{name:"testName",promotionType:"1"},
            convert:data=>{
                let options=[
                  {
                    label:"请选择",
                    value:""
                  }
                ];
                if(data.code=="1"&&data.data){
                  for(let key in data.data){
                    options.push({
                      label:data.data[key],
                      value:key
                    })
                  }
                }
                return options;
            }
          },
          switcher:[
            {
              prop:"sports",
              showValue:3
            }
          ],
          options:[
            {
              label:"休闲食品",
              value:"0"
            },
            {
              label:"家居日化",
              value:"1"
            }
          ],
          placeholder:"请选择分类",
          required:true,
          validates:[
            control=>{
              let param={prop:"sex",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{watchers:true},param);
            }
          ],
        },
        {
          type:"input",
          label:"商品名称",
          prop:"goodsName",
          placeholder:"请输入商品名称",
          defaultValue:"",
          required:true,
          validates:[
            control=>{
              let param={prop:"goodsName",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true,maxlength:5},param);
            }
          ]
        },
        {
          type:"input",
          label:"商品原价",
          prop:"goodsOrgPrice",
          placeholder:"请输入商品原价",
          defaultValue:"",
          required:true,
          validates:[
            control=>{
              let param={prop:"goodsOrgPrice",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5},param);
            }
          ]
        },
        {
          type:"input",
          label:"商品现价",
          prop:"goodsCurPrice",
          placeholder:"请输入商品现价",
          defaultValue:"",
          required:true,
          validates:[
            control=>{
              let param={prop:"goodsCurPrice",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5},param);
            }
          ]
        },
        {
          type:"input",
          label:"商品库存",
          prop:"goodsLib",
          placeholder:"请输入商品库存",
          defaultValue:"",
          required:true,
          validates:[
            control=>{
              let param={prop:"goodsLib",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5},param);
            }
          ]
        },
        {
          type:"radio",
          label:"是否限购",
          prop:"isLimit",
          placeholder:"请输入商品名称",
          defaultValue:"1",
          options:[
            {
              label:"是",
              value:"0"
            },
            {
              label:"否",
              value:"1"
            }
          ],
          required:true,
          validates:[
            control=>{
              let param={prop:"isLimit",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{watchers:true},param);
            }
          ]
        },
        {
          type:"input",
          label:"每人限购",
          prop:"buyLimitNum",
          placeholder:"请输入商品名称",
          defaultValue:"",
          required:true,
          switcher:[
            {
              prop:"isLimit",
              showValue:"0"
            }
          ],
          validates:[
            control=>{
              let param={prop:"buyLimitNum",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5},param);
            }
          ]
        },
        {
          type:"radio",
          label:"是否包邮",
          prop:"free",
          defaultValue:"0",
          options:[
            {
              label:"包邮",
              value:"0"
            },
            {
              label:"不包邮",
              value:"1"
            }
          ],
          placeholder:"请输入商品名称",
          required:true,
          validates:[
            control=>{
              let param={prop:"buyLimitNum",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true},param);
            }
          ]
        },
        {
          type:"select",
          label:"送达说明",
          prop:"arriveInfo",
          placeholder:"送达说明",
          defaultValue:"1",
          required:true,
          options:[
            {
              label:"半小时",
              value:"0"
            },
            {
              label:"1小时",
              value:"1"
            }
          ],
          validates:[
            control=>{
              let param={prop:"arriveInfo",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true},param);
            }
          ]
        },
        {
          type:"checkbox",
          label:"售后说明",
          prop:"afterSale",
          options:[
            {
              label:"7天无理由退换",
              value:"0"
            }
          ],
          placeholder:"请输入名称",
          defaultValue:"2",
          required:true,
          validates:[control=>{
            let param={prop:"afterSale",formModel:this.formModel,grandfather:"afterSale",formGroup:this.formGroup};
            this.baseValidateService.baseValidate(control,{checkboxWatchers:true},param)
          }]
        },
        {
          type:"input",
          label:"商品条码",
          switcher:[{
            prop:"sex",
            showValue:"1"
          }],
          prop:"goodsQurt",
          validates:[
            data=>{
              return this.baseValidateService.baseValidate(data,{required:true,number:"##.##",maxvalue:10,minvalue:0.5})
            }
          ]
        },
       /* {
          type:"checkbox",
          label:"体育运动",
          prop:"sports",
          options:[
            {
              label:"跑步",
              value:"0"
            },
            {
              label:"健身",
              value:"1"
            },
            {
              label:"瑜伽",
              value:"2"
            },
            {
              label:"太极",
              value:"3"}
          ],
          placeholder:"请输入名称",
          defaultValue:"2",
          required:true,
          validates:[control=>{
            let param={prop:"sports",formModel:this.formModel,grandfather:"sports",formGroup:this.formGroup};
            this.baseValidateService.baseValidate(control,{checkboxRequired:true,checkboxWatchers:true},param)
          }]
        },*/
        /*{
          type:"array",
          label:"活动时间",
          prop:"compSizeInnerHeight",
          options:[
            {
              label:"",
              type:"input",
              prop:"compA",
              value:"0"
            },
            {
              label:"至",
              type:"input",
              prop:"compB",
              value:"1"
            },
          ],
          validates:[
            data=>{
              // return this.baseValidateService.baseValidate(data,{required:true,number:"##.##",maxvalue:10,minvalue:0.5})
            }
          ]
        },*/
        {
          label:"头图",
          prop:"firstPic",
          type:"upload",
          multiple:false,
          uploadClass:{myUploadStyle:true},
          require:true,
          defaultValue:"",
          imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
          validates:[control=>{
            return this.baseValidateService.baseValidate(control,{required:true});
          }]
        },
        {
          label:"详情图片",
          prop:"detailPics",
          type:"array",
          multiple:false,
          uploadClass:{myUploadStyle2:true},
          options:[
            {
              label:"",
              prop:"detailA",
              type:"upload",
              value:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailB",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailC",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailD",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailE",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailF",
              type:"upload",
              value:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailG",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailH",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailI",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailJ",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            }
          ],
          validates:[control=>{
            let param={prop:"detailPics",formModel:this.formModel,grandfather:"detailPics",formGroup:this.formGroup};
            return this.baseValidateService.baseValidate(control,{arrayUploadRequired:3},param);
          }]
        },
        {
          label:"商品焦点图",
          type:"array",
          prop:"goodsDetailImages",
          validates:[control=>{
            let param={prop:"goodsDetailImages",formModel:this.formModel,grandfather:"goodsDetailImages",formGroup:this.formGroup};
            return this.baseValidateService.baseValidate(control,{arrayUploadRequired:1},param);
          }],
          options:[
            {
              label:"",
              prop:"detailA",
              type:"upload",
              value:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailB",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailC",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailD",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            },
            {
              label:"",
              prop:"detailE",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
              validates:[control=>{
                console.log(control.value);
                this.baseValidateService.baseValidate(control,{required:true});
              }]
            }
          ]
        },
        {
          label:"商品重量",
          type:"input",
          prop:"goodsWeight",
          validates:[
            control=>{
              let param={prop:"goodsWeight",formModel:this.formModel};
              return this.baseValidateService.baseValidate(control,{required:true,number:"###.###",maxvalue:"9999.99",minvalue:"0.001",maxlength:5},param);
            }
          ]
        },
        {
          label:"描述",
          type:"textarea",
          prop:"goodsDetailInfo",
          validates:[
            data=>{

            }
          ]
        },
        {
          label:"商品发布",
          type:"radio",
          prop:"isPublish",
          defaultValue:"0",
          options:[
            {
              label:"放入仓库",
              value:"0"
            },
            {
              label:"立即上架",
              value:"1"
            }
          ],
          validates:[
            control=>{
              let param={prop:"isPublish",formModel:this.formModel,grandfather:"sports",formGroup:this.formGroup};
              return this.baseValidateService.baseValidate(control,{watchers:true},param);
            }
          ]
        },
        {
          label:"定时上架",
          prop:"timerUpSheep",
          type:"input",
          switcher:[
            {
              prop:"isPublish",
              showValue:"0"
            }
          ],
          defaultValue:"请输入上架时间"
        },
        {
          label:"定时下架",
          prop:"timerDownSheep",
          type:"input",
          defaultValue:"请输入下架时间"
        },
        {
          label:"开始时间",
          prop:"startTimeStr",
          defaultValue:"",
          type:"date",
          chooseConfig:{
            format:'YYYY-MM-DD hh:mm:ss',
            placeholder:'请输入开始时间',
            next:0.5,
            maxelementid:'endTimeStr',
            minelementid:null
          },
          validates:[control=>{
          //let param={prop:"activeTime",formModel:this.formModel,grandfather:"activeTime",formGroup:this.formGroup};
          console.log(control.value)
          //return this.baseValidateService.baseValidate(control,{arrayUploadRequired:1},param);
        }]
        },
        {
          label:"结束时间",
          prop:"endTimeStr",
          defaultValue:"",
          type:"date",
          chooseConfig:{
            format:'YYYY-MM-DD hh:mm:ss',
            placeholder:'请输入开始时间',
            next:0,
            maxelementid:null,
            minelementid:"startTimeStr"
          }
        },
        {
          label:"活动时间",
          type:"array",
          prop:"activeTime",
          options:[
            {
              label:"",
              prop:"activeStartTimeStr",
              defaultValue:"",
              type:"date",
              value:"",
              chooseConfig:{
                format:'YYYY-MM-DD',
                placeholder:'请输入开始时间',
                next:0.5,
                maxelementid:'activeEndTimeStr',
                minelementid:null
              }
            },
            {
              label:"-",
              prop:"activeEndTimeStr",
              defaultValue:"",
              type:"date",
              value:"",
              chooseConfig:{
                format:'YYYY-MM-DD',
                placeholder:'请输入开始时间',
                next:0,
                maxelementid:null,
                minelementid:"activeStartTimeStr"
              }
            }
          ],
          validates:[control=>{
            let param={prop:"activeTime",formModel:this.formModel,grandfather:"activeTime",formGroup:this.formGroup};
            return this.baseValidateService.baseValidate(control,{arrayUploadRequired:1},param);
          }]
        }
      ]
    };
    this.initForm()
  }


  open(){

  }

  close(data){
    console.log("closedata",data)
  }

  serviceArea;
  chooseResult(data){
    console.log("goods form chooseResult",data);
    this.serviceArea=data;
  }

  submit(){
    console.log("sub sub this.formGroup",this.formGroup.value,this.serviceArea)
    this.baseDataService.listData({url:this.formModel.url,param:this.formGroup.value,httpMethod:"post"}).subscribe(data=>{
      console.log(data)
    },error=>{
      console.log(error);
      this.router.navigate(["lotteryList"])
    })
  }
}
